name: 'Terraform'

on:
  push:
    branches: [ "main" ]
#   schedule:
#   - cron: "0 */6 * * *"

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    environment: DEV
    
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false
      env:
        TF_VAR_zone_id: ${{ secrets.TF_CLOUDFLARE_ZONE_ID }}
        TF_VAR_api_token: ${{ secrets.TF_CLOUDFLARE_API_TOKEN }}

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      env:
        TF_VAR_zone_id: ${{ secrets.TF_CLOUDFLARE_ZONE_ID }}
        TF_VAR_api_token: ${{ secrets.TF_CLOUDFLARE_API_TOKEN }}
